---
extends: default

# Ignore template files since they contain Go template syntax
ignore: |
  templates/

rules:
  line-length:
    max: 120
    level: warning
  indentation:
    spaces: 2
    indent-sequences: true
  truthy:
    allowed-values: ['true', 'false']
